##
## simulation
##

# epi rates
"β" = 0.5
"γ" = 0.1
"λ" = 0.05
"δ" = 0.07
"κ" = 0.0005
"ϝ" = 10.0

# utility
"ψ" = 500.0
"σ" = 0.3

# behavioral
"ρ" = 0.15
zi = 1.5

# testing
p0 = 0.1
pr = 0.01

# time varying
"β0" = 0.3
"βr" = 0.03
"ψ0" = 1.0
"ψr" = 0.03

##
## estimation
##

# measurement error
"σa" = 10
"σo" = 10

# lockdown levels
zb1 = 0.8
zb2 = 0.9
zb3 = 1.0
